graph LR

  User -->|HTTP/HTTPS| ALB

  subgraph AWS
    ALB[ALB - Application Load Balancer]
    EKS[EKS Control Plane]

    subgraph PrivateSubnets
      NG1[Managed Node Group 1]
      NG2[Managed Node Group 2]
    end

    subgraph PublicSubnets
      ALB
    end

  end

  ALB -->|Routes traffic| NG1
  ALB -->|Routes traffic| NG2

  EKS --> NG1
  EKS --> NG2

  NG1 --> WebAppPods[WebApp Pods]
  NG2 --> WebAppPods

  Notes["
  • Web Application Pods  
  • HPA scales pods  
  • Cluster Autoscaler scales nodes
  "]

  WebAppPods --- Notes

